language: ruby
cache: bundler
dist: trusty
rvm:
  - 2.5.1
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database auth0app_test;' -U postgres
  - gem install bundler
  - gem update bundler
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake