version: '3.8'
volumes:
  postgres-data:
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: 210295
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: foreman start -f Procfile.dev -p 3000
    volumes:
        - .:/project
        - type: tmpfs
          target: /project/tmp/pids/
    ports:
        - "3000:3000"
        - "35729:35729"
    depends_on:
      - db